### ISSUE TITLE
Failed to compile /: Can't stat /

### ISSUE THREAD

**Issue by chenfengyanyu** [electron-userland/electron-compile#288]
I use react-router, but can't refresh.otherwise,it failed to compile.Here is my code:
```jsx
<Router>
     <Switch>
          <Route path="/" exact component={Upload} />
          <Route path="/list" component={ListPage} />
          <Redirect to="/" />
      </Switch>
</Router>
```
Did anyone know what had happened? And what should I do?

**Comment by MarshallOfSound** [comment]
@chenfengyanyu You have to use the memory router or the hash router, otherwise you will be navigating around on the `file://` protocol.

**Comment by chenfengyanyu** [comment]
@MarshallOfSound You are right, thank you very much!
